from __future__ import annotations

from ..markers import replace_marked_section
from ..model import CoverageReport, LocaleGuardConfig
from ..rendering import html_flag, progress_bar, relative_link


def render_readme_body(config: LocaleGuardConfig, report: CoverageReport) -> str:
    columns = ["Language"]
    if config.readme.show_progress:
        columns.append("Progress")
    if config.readme.show_counts:
        columns.append("Files")
    if config.readme.show_percentages:
        columns.append("Coverage")

    alignments = ["---"] + ["---:" for _ in columns[1:]]
    lines = [
        "## Documentation Languages",
        "",
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(alignments) + " |",
    ]

    canonical_label = config.canonical.name
    if config.readme.show_flags:
        flag_path = config.output.flag_directory / f"{config.canonical.country.lower()}.svg"
        canonical_label = f"{html_flag(relative_link(config.readme.path, flag_path), config.canonical.name)} {canonical_label}"

    canonical_row = [canonical_label]
    if config.readme.show_progress:
        canonical_row.append("██████████")
    if config.readme.show_counts:
        canonical_row.append(f"{report.canonical_total} / {report.canonical_total}")
    if config.readme.show_percentages:
        canonical_row.append("Canonical")
    lines.append("| " + " | ".join(canonical_row) + " |")

    for coverage in report.languages.values():
        label = coverage.name
        if config.readme.show_flags:
            flag_path = config.output.flag_directory / f"{coverage.country.lower()}.svg"
            label = f"{html_flag(relative_link(config.readme.path, flag_path), coverage.name)} {label}"
        row = [label]
        if config.readme.show_progress:
            row.append(progress_bar(coverage.percentage))
        if config.readme.show_counts:
            row.append(f"{coverage.present} / {coverage.total}")
        if config.readme.show_percentages:
            row.append(f"{coverage.percentage:.1f}%")
        lines.append("| " + " | ".join(row) + " |")

    lines.extend([
        "",
        "_Generated by [LocaleGuard](https://github.com/phpwalter/locale-guard). Do not edit this section manually._",
    ])
    return "\n".join(lines)


def expected_readme(config: LocaleGuardConfig, report: CoverageReport) -> str | None:
    if not config.readme.enabled:
        return None
    if not config.readme.path.exists():
        raise FileNotFoundError(f"README file not found: {config.readme.path}")
    text = config.readme.path.read_text(encoding="utf-8")
    return replace_marked_section(
        text,
        config.readme.start_marker,
        config.readme.end_marker,
        render_readme_body(config, report),
    )
