from __future__ import annotations

from ..model import CoverageReport, LocaleGuardConfig


def render_status_report(config: LocaleGuardConfig, report: CoverageReport) -> str:
    lines = [
        "# Localization Status",
        "",
        "This file is generated by LocaleGuard. Do not edit it manually.",
        "",
        f"Canonical language: **{config.canonical.name} (`{config.canonical.code}`)**",
        f"Canonical documents: **{report.canonical_total}**",
        "",
        "## Coverage",
        "",
        "| Language | Present | Missing | Total | Coverage |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for coverage in report.languages.values():
        lines.append(
            f"| {coverage.name} (`{coverage.code}`) | {coverage.present} | {coverage.missing} | {coverage.total} | {coverage.percentage:.1f}% |"
        )

    for code, coverage in report.languages.items():
        missing = [doc.relative_path.as_posix() for doc in report.documents if doc.translations.get(code) is None]
        lines.extend([
            "",
            f"## {coverage.name}",
            "",
            f"Coverage: **{coverage.present}/{coverage.total} ({coverage.percentage:.1f}%)**",
            "",
        ])
        if not missing:
            lines.append("All canonical documents have localized counterparts.")
        else:
            lines.append(f"Missing {len(missing)} document(s):")
            lines.append("")
            lines.extend(f"- `{path}`" for path in missing)

    lines.append("")
    return "\n".join(lines)
